import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/utils/context/AuthContext";
import { LinkProvider } from "@/utils/context/LinkContext";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={instrumentSans.className}>
        <AuthProvider>
          <LinkProvider>
            {children}
          </LinkProvider>
        </AuthProvider>
      </body>
    </html>


  );
}
